version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
validators:
- name: alice
  bonded: 100000000stake
  config:
    moniker: "eth-enabled-node"
  app:
   # chain will not function propely without this variable pointing to a node URL
    ethereum-rpc-url: "<eth_rpc_node_url>"
build:
  main: cmd/ethclientd